name: Build and Release

on:
  push:
    tags:
      - "v*.*.*" # Trigger only on version tags
  workflow_dispatch:
    inputs:
      build_installer:
        description: "Build the Windows installer"
        type: boolean
        required: true
        default: true
      build_extension:
        description: "Build the custom VS Code extension"
        type: boolean
        required: true
        default: false
      build_libraries:
        description: "Compress the Rocq LnA and SCcoq libraries"
        type: boolean
        required: true
        default: false

env:
  COQREGTESTING: y

jobs:
  ###############################################################################
  # Builds Windows installer
  ###############################################################################
  build-windows-installer:
    name: Windows
    runs-on: windows-latest
    if: ${{ inputs.build_installer }}
    strategy:
      fail-fast: false
      matrix:
        coq-platform-pick:
          - "8.19~2024.10"

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Git checkout install scripts
        uses: actions/checkout@v4
        with:
          path: main

      - name: Git checkout Coq platform
        uses: actions/checkout@v4
        with:
          repository: coq/platform
          path: platform

      - name: Download EnVar Plugin
        run: |
          Invoke-WebRequest -Uri "https://github.com/GsNSIS/EnVar/releases/download/v0.3.1/EnVar-Plugin.zip" -OutFile "EnVar.zip"
          Expand-Archive -Path "EnVar.zip" -DestinationPath "platform\windows\envar"
          tree .

      - name: Set switch name in coq platform
        shell: cmd
        # We need to output without a (windows style new line here) else bash will complain AND we rely on the fact that the file has a trailing new line.
        run: |
          echo | set /p dummyName="COQ_PLATFORM_SWITCH_NAME=LnA" >> platform\package_picks\coq_platform_switch_name.sh
          type platform\package_picks\coq_platform_switch_name.sh

      - name: Set default install directory
        shell: cmd
        run: |
          sed -i 's/\s\sInstallDir\s"C:\\\${MY_PRODUCT}"/  InstallDir "C:\\\cygwin_LnA\\\home\\\runneradmin\\\.opam\\\LnA"/g' platform/windows/Coq.nsi
          cat platform/windows/Coq.nsi

      - name: Run coq platform make windows
        shell: cmd
        run: platform\coq_platform_make_windows.bat -destcyg=C:\cygwin_LnA -arch=64 -extent=b -parallel=p -jobs=2 -vst=n -compcert=n -pick="${{matrix.coq-platform-pick}}" -set-switch=y

      - name: Patch installer
        shell: cmd
        run: |
          copy main\installer\* C:\cygwin_LnA\platform\
          C:\cygwin_LnA\bin\bash --login -c "/platform/patch_installer.sh"

      - name: Install LnA
        shell: cmd
        run: |
          mkdir C:\cygwin_LnA\home\runneradmin\LnA
          copy main\library\* C:\cygwin_LnA\home\runneradmin\LnA
          C:\cygwin_LnA\bin\bash --login -c "ls && opam pin add -y ./LnA"

      - name: Install SCcoq
        shell: cmd
        run: |
          mkdir C:\cygwin_LnA\home\runneradmin\SCcoq
          copy main\SC-library\* C:\cygwin_LnA\home\runneradmin\SCcoq
          C:\cygwin_LnA\bin\bash --login -c "ls && opam pin add -y ./SCcoq"

      - name: Create installer
        shell: cmd
        run: |
          tree /f
          C:\cygwin_LnA\bin\bash --login -c "cd /platform && cat windows/create_installer_windows.sh && windows/create_installer_windows.sh && mkdir /cygdrive/c/installer && cp windows_installer/*exe /cygdrive/c/installer/"

      # - name: Sign the installer
      #   if: always()
      #   run: |
      #     New-Item -ItemType directory -Path certificate
      #     Set-Content -Path certificate\certificate.txt -Value '${{ secrets.CODE_SIGNING_CERTIFICATE }}'
      #     certutil -decode certificate\certificate.txt certificate\certificate.pfx
      #     & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /f certificate\certificate.pfx /p '${{ secrets.CODE_SIGNING_CERTIFICATE_PASS }}' C:\installer\*.exe
      #     Remove-Item -Path certificate\*

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "LnA-Windows-installer"
          path: C:\installer\*.exe

  ###############################################################################
  # Builds VS Code Extension
  ###############################################################################
  build-vsix:
    runs-on: ubuntu-latest
    if: ${{ inputs.build_extension }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          cd extension
          npm install

      - name: Package `.vsix`
        run: |
          cd extension
          npx vsce package

      - name: Upload `.vsix` as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-artifact
          path: extension/*.vsix

  ###############################################################################
  # Builds the Rocq library LnA
  ###############################################################################
  archive-libraries:
    runs-on: ubuntu-latest
    if: ${{ inputs.build_libraries }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5

      - name: Create LnA library archive
        run: |
          cd library
          VERSION=${GITHUB_REF_NAME#v}
          git archive -o ../LnA-$VERSION.tar.gz --prefix="LnA-$VERSION/" $GITHUB_SHA .

      - name: Create SCcoq library archive
        run: |
          cd SC-library
          git archive -o ../SCcoq.tar.gz $GITHUB_SHA .

      - name: Upload `.tar.gz` as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: library-archive
          path: ./*.tar.gz

  ###############################################################################
  # Collects all artifacts and puts them on the releases page
  ###############################################################################
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' }}
    needs: [build-windows-installer, build-vsix, archive-libraries] # Depends on other jobs
    steps:
      - name: Download Extension Artifact
        uses: actions/download-artifact@v4
        with:
          name: vsix-artifact
          path: ./release-assets

      - name: Download Installer Artifact
        uses: actions/download-artifact@v4
        with:
          name: LnA-Windows-installer
          path: ./release-assets

      - name: Download Library Archive Artifact
        uses: actions/download-artifact@v4
        with:
          name: library-archive
          path: ./release-assets

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-assets/*
          draft: true
