name: Run tests

on:
  push:
    branches:
      - "*"
    paths:
      - "extension/src/**"

jobs:
  test-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci
        working-directory: ./extension

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Run Tests
        run: |
          export DISPLAY=:99
          xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' npm run test
        working-directory: ./extension
